service: sample-app
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:us-east-1:*:*'
plugins:
  - serverless-offline
functions:
  app:
    handler: app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
  getback:
    handler: app.handler
    events:
      - http: POST /api/v1/getback
  info:
    handler: app.handler
    events:
      - http: GET /api/info
resources:
  Resources:

      
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AssetValue
        AttributeDefinitions:
          - AttributeName: assetId
            AttributeType: S
        KeySchema:
          - AttributeName: assetId
            KeyType: HASH
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
