service: sample-app
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:us-east-1:*:*'

  # usagePlan: # Optional usage plan configuration
  #   quota:
  #     limit: 5000
  #     offset: 2
  #     period: MONTH
  #   throttle:
  #     burstLimit: 200
  #     rateLimit: 100
plugins:
  - serverless-offline
package:
  exclude:
    - .git/**
    - prediction-ui/**
functions:
  # finn:
  #   handler: services/finnhub.handler
  #   events:
  #     - http: 
  #         path: finn
  #         method: ANY
  #         cors: true
  finn:
    handler: services/finnhub.handler
    events: 
      - http: 
          path: /finn
          method: ANY
          cors: true
      - http: 
          path: /finn/{proxy+}
          method: ANY
          cors: true
    environment:
      finnhubApiKey: ${file(./config/finnhub.yml):finnhub.finnhubApiKey}
  app:
    handler: app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
resources:
  Resources:

      
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AssetValue
        AttributeDefinitions:
          - AttributeName: assetId
            AttributeType: S
        KeySchema:
          - AttributeName: assetId
            KeyType: HASH
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
